### ISSUE TITLE
Define a purpose or overal mission for this project

### ISSUE THREAD

**Issue by dfirebaugh** [dfirebaugh/code-improv#6]
This is a project with no rules... well, now there are a few rules.

With some kind of mission or purpose driving this project, it might make for better contributions.  Maybe this could actually be something useful.

Feel free to brainstorm here

Put details in README

**Comment by Athulus** [comment]
I want this to turn into a website where all of the code someone commits is available for people to interact with there

**Comment by dfirebaugh** [comment]
That sounds cool.  How would one interact with the code?

**Comment by Athulus** [comment]
my thought was just to let people call the functions that people are posting and see what they return.

do you have any other ideas that might be fun?

**Comment by Athulus** [comment]
I was looking at using rpc to make a server that could call all of the functions in different languages

**Comment by dfirebaugh** [comment]
interesting
could you just use some kind of repl to run the code?

**Comment by Athulus** [comment]
Yeah we could definitely integrate a replacement into the website. I would like to be able to call all of the code from one replacement though, independent of language
